name: 'Pages build and deployment'
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v2
    - name: Build & Publish
      uses: ZanderZhao/gitbook-action@master
      with:                                   #    or fork this repo and use YourName/gitbook-action@master
        token: ${{ secrets.GITHUB_TOKEN }}  # -> remember add this in settings/secrets as following
        source_dir: '/Docs'
